{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vayr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vayr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vayr/vayr_{{ version }}.tar.gz
  sha256: 9b61342f327d5f5fcb712323d5b7b6361ebf7ed84f3f56395c9eed2d05b1a594

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-packcircles >=0.3.7
    - r-withr >=2.1.1
  run:
    - r-base
    - r-ggplot2 >=3.0.0
    - r-packcircles >=0.3.7
    - r-withr >=2.1.1

test:
  commands:
    - $R -e "library('vayr')"           # [not win]
    - "\"%R%\" -e \"library('vayr')\""  # [win]

about:
  home: https://alexandercoppock.com/vayr/index.html
  license: GPL-2.0-only
  summary: Position adjustments for 'ggplot2' to implement "visualize as you randomize" principles,
    which can be especially useful when plotting experimental data.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: vayr
# Title: Extensions for 'ggplot2' to Visualize as You Randomize
# Version: 1.0.0
# Authors@R: c(person("Alexander", "Coppock", , "acoppock@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0002-5733-2386")), person("Elias", "Hyde", , "eliasworrallhyde@gmail.com", role = "ctb"))
# Description: Position adjustments for 'ggplot2' to implement "visualize as you randomize" principles, which can be especially useful when plotting experimental data.
# License: GPL-2 | file LICENSE
# URL: https://alexandercoppock.com/vayr/index.html
# Depends: R (>= 4.1.0)
# Imports: ggplot2 (>= 3.0.0), packcircles (>= 0.3.7), withr (>= 2.1.1)
# Suggests: dplyr, estimatr, knitr, patchwork, randomizr, rmarkdown, sessioninfo, testthat, tibble, tidyverse
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.3.2
# NeedsCompilation: no
# Packaged: 2025-04-10 18:06:23 UTC; ac2595
# Author: Alexander Coppock [aut, cre, cph] (<https://orcid.org/0000-0002-5733-2386>), Elias Hyde [ctb]
# Maintainer: Alexander Coppock <acoppock@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-04-15 20:10:05 UTC
